= memo

== 参照元

* https://qiita.com/thesugar/items/01896c1faa8241e6b1bc#nextjs-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB[大幅にリニューアルされた Next.js のチュートリアルをどこよりも早く全編和訳しました]
* https://nextjs.org/learn/basics/create-nextjs-app[Learn Next.js (公式)]

== 初期化

[source,bash]
.PJ初期化
----
npm init next-app nextjs-blog --example "https://github.com/zeit/next-learn-starter/tree/master/learn-starter" # <1>
# or
yarn create next-app nextjs-blog --example "https://github.com/zeit/next-learn-starter/tree/master/learn-starter"
----
<1> nextjs-blog ディレクトリを生成して初期化する。

[source,bash]
.開発サーバ起動
----
npm run dev
# or
yarn dev
----

== pages

[quote]
____
Next.js では、ページとは pages ディレクトリに存在するファイルからエクスポートされる React コンポーネントです。

ページは ファイル名 に基づいてルーティングに関連づけられます。例えば、開発時は：

* pages/index.js は / にルーティングされます。
* pages/posts/first-post.js は /posts/first-post としてルーティングされます。
____

== Link compornent

[source]
----
Read <Link href="/posts/first-post"><a>this page!</a></Link>
----

Link コンポーネントは **クライアントサイドのページ遷移(ナビゲーション)** として機能する。


[quote]
____
クライアントサイドのナビゲーションとは、ページ遷移が JavaScript を使って 行われることを意味し、ブラウザによって行われるデフォルトのページ遷移よりも高速です。

Next.js のアプリの外にある外部のページにリンクを貼る必要があるときは、 Link 無しで <a> タグだけを使ってください。
className といった属性を加える必要があるときは、 Link タグでなく、a タグに加えてください。
____

注意点として。下記のようにhtmlのタグとreactのタグで頭文字の大文字小文字で判別するケースがよくある。

[horizontal]
link::: htmlが提供するスタイルシートを読み込むためのタグ
Link::: Reactが提供するリンク用のタグ

== CSS スタイリング

[source]
----
<style jsx>{`
   ...
`}</style>
----

[quote]
____
これは styled-jsx というライブラリを使用しています。これは「CSS-in-JS」のライブラリ、すなわち、React コンポーネント内で CSS を書くことができ、CSS スタイルがスコープ付けられます（他のコンポーネントは影響を受けません）。
____

CSSモジュール::
+
--
* CSS モジュールを使うと __CSS ファイルを React コンポーネントの中でインポートすることができるように__ なる
* CSS モジュールを使用するためには、 **CSS ファイル名は .module.css で終わる** 必要がある
* CSS モジュールは自動的に一意のクラス名を生成する
** つまり、CSS モジュールを使っているかぎりは、クラス名の衝突を気にする必要はない
--
+
[source, javascript]
----
import styles from './layout.module.css' // <1>

export default function Layout({ children }) { // <3>
  return <div className={styles.container}>{children}</div> // <2>
}
----
<1> `styles` として CSS モジュールをインポートする
<2> `styles.<class-name>` を `className` として使う
<3> 分割代入。引数のオブジェクトから `children` プロパティを変数 `children` として定義

グローバルな CSS::
+
--
* グローバルな CSS を読み込む場合は **pages ディレクトリ配下の _app.js** に記載する
** 逆に、ここ以外の場所ではグローバルな CSS を **インポート** できない！(あくまでもインポートができない)
*** CSS ファイル自体はどこでも、どんな名前でもOK
* App コンポーネントはすべてのページに共通するトップレベルのコンポーネント
* App コンポーネントで状態を保持することもできる
--
+
--
[source, javascript]
----
export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />
}
----
--
+
--
IMPORTANT: `_app.js` を **追加した** ときはサーバーの再起動が必要！
--

== プリレンダリング

[quote]
____
開発モード（npm run dev あるいは yarn dev を実行したとき）では、静的生成を使用しているページであっても、すべてのページが毎回のリクエストごとにプリレンダリングされます。
____

* next.js ではページ単位でサーバサイドレンダリングか静的生成を選択可能
* デフォルトでは静的生成をするべき
** マーケティングページ
** ブログ記事
** E コマースの商品リスト
** ヘルプやドキュメンテーション
* 必要に応じてサーバサイドレンダリングを選択する
** 頻繁に更新されるデータを表示するページ
** 毎回のリクエストごとに内容が変わるページ

* next.js では、ビルド時に外部からデータを取得して静的ページを生成できる

データありの静的生成 (getStaticProps)::
+
--
[source, javascript]
----
export default function Home(props) { ... }

export async function getStaticProps() {
    // ファイルシステムや API、DB などから外部データを取得する
    const data = ...

    // `props` キーに対応する値が `Home` コンポーネントに渡される
    return {
        props: ...
    }
}
----
--
+
--
* `getStaticProps` は **本番環境用のビルド時に実行** される
** 逆に言うと、ビルド時にデータのソースにアクセスできる必要がある
* 上記のサンプルでは外部データを取得して `Home` の `props` に渡している
* `getStaticProps` は **ページ からのみ export できる**
--
+
--
[quote]
____
このページにはいくつか外部に依存しているデータがあるよ。だからビルド時にこのページをプリレンダリングするときは、まずその依存関係をしっかり解決してよ！
____
--
+
--
NOTE: 開発環境では、getStaticProps は毎回のリクエストごとに実行されます。
--

== サーバーサイドレンダリング

サーバーサイドレンダリングでは `getServerSideProps` を使う。

[source, javascript]
----
export async function getServerSideProps(context) { // <1>
  return {
    props: {
      // コンポーネントに渡すための props
    }
  }
}
----
<1> `context` にはリクエストの特定のパラメータが含まれる

あとは `getStaticProps` と同様(のはず)。

== クライアントサイドレンダリング

クライアントサイドレンダリングは、ユーザーのダッシュボードページを作るときなどに有効。

* ダッシュボードはプライベートなものでユーザーに固有のページである
* SEO は関係ない
* ページがプリレンダリングされる必要はない
* データは頻繁に更新されリクエスト時のデータ取得を必要とする

クライアントサイドでデータ取得をする場合は **SWR** というデータフェッチ用の React フックを推奨。
下記に対応している。

* キャッシング
* 再検証（revalidation）
* フォーカストラッキング
* インターバルを開けた再フェッチ など

.サンプル
[source, javascript]
----
import useSWR from 'swr'

function Profile() {
  const { data, error } = useSWR('/api/user', fetch)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  return <div>hello {data.name}!</div>
}
----

== 動的ルーティングによる静的ページの生成

サンプルの要件としては次の通り。

* 各投稿のパスは `/posts/<id>`
* `<id>` はソースとなるファイル名を利用する

実現するには下記の手順をたどる。

--
* ソースに応じて動的にパスが変わる React コンポーネントを準備
* React コンポーネント内では下記を実装
[horizontal]
`getStaticPaths`:: パス (`/posts/<id>`) を生成する
`getStaticProps`:: パスに紐づく個々のページのデータを取得して、
React コンポーネントの default へ渡す
--

getStaticPaths::
+
--
[source,javascript]
----
export async function getStaticPaths() {
  const paths = getAllPostIds()
  return {
    paths,
    fallback: false
  }
  // `paths` は以下のような配列を返す必要がある:
  // [
  //   {
  //     params: {
  //       id: 'ssg-ssr'
  //     }
  //   },
  //   {
  //     params: {
  //       id: 'pre-rendering'
  //     }
  //   }
  // ]
}
----
--
+
--
NOTE: 開発環境では、getStaticPaths は毎回のリクエストごとに実行されます。
--
+
--
fallback について::
[horizontal]
false::: getStaticPaths から return されていないあらゆるパスは、アクセスすると 404 ページ になる
true::: getStaticPaths から return されたパスはビルド時に HTML としてレンダーされる。
--

getStaticProps::
+
--
[source,javascript]
----
export async function getStaticProps({ params }) {
  // `getStaticPaths` がある場合には自動的に `params` が渡ってくる？
  const postData = getPostData(params.id)
  return {
    props: {
      postData
    }
  }
  // `postData` は以下のようなオブジェクトを返す必要がある:
  // {
  //   id, // <1>
  //   ...matterResult.data // <2>
  // }
}
----
<1> 省略プロパティ名。 `"id": id` の省略記法。
<2> スプレッド構文。オブジェクトが展開される。
--

dangerouslySetInnerHTML::
`dangerouslySetInnerHTML` は React の DOM 要素。
動的に html を生成する。
XSSのリスクがあるため `dangerously` の名称。

動的ルーティング持ったページにリンクを貼るには `Link` コンポーネントを使う。

[source,javascript]
----
<li className={utilStyles.listItem} key={id}>
  <Link href="/posts/[id]" as={`/posts/${id}`}> // <1> <2>
    <a>{title}</a>
  </Link>
  <br />
  <small className={utilStyles.lightText}>
    <Date dateString={date} />
  </small>
</li>
----
<1> href には [id] と定義。(React 側で自動的に変数を解釈する？)
<2> as prop には実際のパス。

[quote]
____
独自の 404 ページを作成するには、pages/404.js を作成してください。このファイルはビルド時に静的に生成されます。
____

[source,javascript]
----
// pages/404.js
export default function Custom404() {
  return <h1>404 - Page Not Found</h1>
}
----

== API ルート

[source,javascript]
----
export default (req, res) => { // <1> <2>
  res.status(200).json({ text: 'Hello' })
}
----
<1> req はリクエストデータで http.IncomingMessage のインスタンス
<2> res はレスポンスデータで http.ServerResponse のインスタンス

API ルートはサーバーサイドで処理している模様。
なので、 `getStaticProps` や `getStaticPaths` といった静的生成の仕組みは使うべきではない。

TIP: つまり、 Next を使えば、Javascript で簡易なWebサーバーも作れるかも？

== TypeScript

. PJルートに `tsconfig.json` を作る
. install
+
--
[source,bash]
----
# npm を使っている場合
npm install --save-dev typescript @types/react @types/node

# Yarn を使っている場合
yarn add --dev typescript @types/react @types/node
----
--
+
--
[WARNING]
install しないとサーバー起動時に `It looks like you're trying to use TypeScript but do not have the required package(s) installed.` といったエラーがでる。
--
. installl 後にサーバー起動

[WARNING]
自動生成される `next-env.d.ts` はいじらないこと。

引数などにて、必須だけど使わない引数には `_` を用いるのがスタンダード。？

[source,javascript]
----
import { NextApiRequest, NextApiResponse } from 'next'

export default (_: NextApiRequest, res: NextApiResponse) => {
  res.status(200).json({ text: 'Hello' })
}
----

パッケージ内や DefinitelyTypes に型定義がないライブラリは、トップレベルに global.d.ts ファイルを作成して型宣言を加える。

.global.d.ts
[source,javascript]
----
declare module 'remark-html' {
  const html: any
  export default html
}
----

== フォルダ構成

[source,bash]
----
$ tree -a -I "node_modules|\.next|\.git" --charset unicode
.
|-- .gitignore
|-- README.md
|-- components // <13>
|   |-- date.tsx
|   |-- layout.module.css // <4>
|   `-- layout.tsx
|-- global.d.ts // <16>
|-- lib // <9>
|   `-- posts.tsx
|-- memo.adoc
|-- next-env.d.ts // <15>
|-- package-lock.json
|-- package.json
|-- pages // <1>
|   |-- _app.tsx <5>
|   |-- api // <11>
|   |   `-- hello.tsx // <12>
|   |-- index.tsx // <2>
|   `-- posts
|       `-- [id].tsx // <10>
|-- posts // <8>
|   |-- pre-rendering.md
|   `-- ssg-ssr.md
|-- public // <3>
|   |-- favicon.ico
|   |-- images
|   |   `-- profile.jpg
|   `-- vercel.svg
|-- styles
|   |-- global.css // <6>
|   `-- utils.module.css // <7>
|-- tsconfig.json // <14>
`-- yarn.lock
----
<1> (規約) Next.js がページとしてエクスポートする React コンポーネント。
pages ディレクトリ内のファイル名にもとづいてルーティングをする。(ファイルシステムルーティング)
<2> 例えば `/` にアクセスすると、この `index.js(or index.tsx)` を表示する。
<3> (規約) 静的な asset を管理する。
pages ディレクトリと同様に、public 内のファイルはアプリケーションのルート（root, `/`）から参照することができる。
<4> (規約) `.module.css` は React における命名規則。
<5> (規約) すべてのページに共通するトップレベルのコンポーネント。
状態の保持や、グローバルな CSS をインポートすることができる。
<6> グローバルな CSS はどこにでも配置できるが、インポートしてよいのは _app.js(or tsx) のみ。
<7> 複数のコンポーネントからインポートされる css モジュール。
<8> ブログの元データファイル群。
<9> アプリ内で共有するライブラリ群。主に logic に関するファイル群を管理する。
<10> (規約) [ で始まり ] で終わるページは、Next.js では動的なページになる。
この場合、 `/posts/<id>` のエンドポイントでアクセスできる。
<11> API ルート用のディレクトリ。規約ではないがスタンダードな実装。
<12> 例えば `/api/hello` にアクセスすると、このファイル内の処理を実行する。
<13> アプリ内で共有するコンポーネント群。主に view に関するファイル群を管理する。
<14> TypeScript 用の config ファイル。カスタマイズ可能。
<15> TypeScript 用の config ファイル。編集禁止。
<16> パッケージ内や DefinitelyTypes に型定義がないパッケージは、トップレベルに global.d.ts ファイルを作成して型宣言を加える

== その他

import のブラケットについて::
https://stackoverflow.com/questions/36795819/when-should-i-use-curly-braces-for-es6-import

コマンド群::
+
--
[source,bash]
----
npm init next-app nextjs-blog --example "https://github.com/zeit/next-learn-starter/tree/master/learn-starter"

npm run dev
# or
yarn dev

npm install classnames

npm install sass

npm install gray-matter

npm install remark remark-html

npm install date-fns

npm run build

npm run start

npm install --save-dev typescript @types/react @types/node
----
--
